leadr_key = "<C-g>"
print_sequence = true

[shortcuts.co]
command = "tar -cvf archive.tar.gz "
description = "Compress files to tar.gz"

[shortcuts.cl]
command = "clear"
description = "Clear the terminal screen"
execute = true

[shortcuts.ex]
command = "tar -xzvf "
description = "Extract tar.gz file"

[shortcuts.ga]
command = "git add ."
description = "Git add all"
execute = true

[shortcuts.gc]
command = 'git commit -m "#CUROSR"'
description = "Create a new git commit"

[shortcuts.gg]
command = "lazygit"
description = "LazyGit"
execute = true

[shortcuts.gl]
command = "git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
description = "Compact Git log"
execute = true

[shortcuts.gp]
command = "git push"
description = "Git push"
execute = true

[shortcuts.gs]
command = "git status"
description = "Git status"
execute = true

[shortcuts.id]
command = "date +%Y-%m-%d"
description = "Insert current date in YYYY-MM-DD format"
insert_type = "Insert"
evaluate = true

[shortcuts.ss]
command = "sudo "
description = "Prepend sudo to command"
insert_type = "Prepend"
